# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-case-conflict
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args:
          [
            "--branch",
            "main",
            "--pattern",
            "^(feature|bugfix|improvement|library|prerelease|release|hotfix)/_[a-z0-9._-]+$",
          ]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=250"]


  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   # # type: ignore can be used to suspress mypy checks
  #   hooks:
  #     - id: mypy
        # args: [--show-error-codes, --ignore-missing-imports]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    # noqa or # noqa: E234 can be used to suspress flake8 checks
    hooks:
      - id: flake8
        args: [
          "--max-line-length=250",
          "--ignore=E305",
          "--max-complexity=10",
          "--filename=*.py",
          "--extend-exclude=./bot_service/src/chainlit_data_pers/*.py",
        ]

  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #     - id: pydocstyle

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.11'  # or any later Vulture version
    hooks:
      - id: vulture
        args: [
          ".",
          "--min-confidence=61",
          "--exclude=/src/chainlit_data_pers/"
        ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: [ --exclude, /tests ]