version: '3'

services:
  app_backend:
    container_name: manage_app_backend
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile.back
    ports:
      - 8000:8000
    networks:
      - manage-network
    restart: "unless-stopped"
    env_file:
      - .env.dev
    
  app_frontend:
    container_name: manage_app_frontend
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile.front
    env_file:
      - .env.dev
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - 8502:8502
    networks:
      - manage-network 
    restart: "unless-stopped"
    depends_on:
      - app_backend

networks:
  manage-network:
    external: True