[sources.in]
type = "stdin"

[sinks.file]
inputs = ["in"]
type = "file"
compression = "none"
encoding.codec = "text"
path = "vector-%Y-%m-%d.log"

[sinks.out]
inputs = ["in"]
type = "console"
encoding.codec = "text"
