"""First commit

Revision ID: 0fee1f3549af
Revises: 75f0f58e6886
Create Date: 2023-09-10 16:35:35.506754

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0fee1f3549af"
down_revision: Union[str, None] = "75f0f58e6886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("file_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "extension", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "upload_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("file_id", name="file_pkey"),
    )
    # ### end Alembic commands ###
