name: ci
on: [push, pull_request]

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install deps
        run: make deps
      - name: Run CI test
        run: make ci
        
