name: Continous Intergration
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  lint_format_secure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
            ref: ${{ github.head_ref || github.ref_name }}

      - name: Format, lint and security checkss
        if: github.event_name == 'pull_request'
        run: |
          echo "Running CI steps.."
          pip3 install pre-commit
          git branch
          ls -la
          pre-commit run --all-files
      #